name: test-env-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pring debug information
        run: |
          echo "Python version: $(python --version)"
          echo "Pip version: $(pip --version)"
          echo "Installed packages:"
          pip list

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'test_app_release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "test_app_release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: github.ref_type == 'release'  
